收到文件后延迟处理
wechaty/puppet-xp pull request #173
Opened 2023-02-19 09:24 UTC by wenxiangjiang

当收到文件消息后，在文件还未下载成功时便调用 `messageFile` 会产生 `no such file or directory` 错误，这种情况基本 100% 出现，因此可以在真正处理前做 1.5s ~ 3s 延迟处理。

2023-02-19 09:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/puppet-xp?pullRequest=173) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/puppet-xp?pullRequest=173) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/puppet-xp?pullRequest=173) it.</sub>

2023-02-20 03:03 UTC, choogoo commented
@wenxiangjiang This is a known problem. Delaying messages on puppet is not the best solution. A better solution is to set file download completion detection in puppet, and push a message to onMessage when the file is downloaded successfully. In this The recommended solution before the implementation is to set a delay when the client receives the picture message and then get the picture. Thank you for your contribution~

2023-02-20 03:20 UTC, wenxiangjiang commented
@choogoo Yes, it is the best solution to be able to monitor when the file download is complete. Delay can only reduce the chance of error, but it cannot be completely avoided.

2023-02-20 03:30 UTC, choogoo commented
So we will not accept this pr for the time being, because setting a delay when receiving picture messages continuously will also cause the system to slow down receiving other messages, thanks again, and hope that we will have a better way to solve this problem in the future.

2023-02-20 03:46 UTC, atorber requested changes
This is a temporary solution, we look forward to a better solution.

2023-02-20 03:46 UTC, closed without merging