fix: Fix incorrect display version number in README
wechaty/puppet-xp pull request #189
Opened 2023-10-12 09:12 UTC by GodMeowIceSun

2023-10-12 09:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/puppet-xp?pullRequest=189) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/puppet-xp?pullRequest=189) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/puppet-xp?pullRequest=189) it.</sub>

2023-10-12 10:14 UTC, huan commented
## Wechaty Contributors Nomination

Link to https://github.com/wechaty/PMC/issues/16

2023-10-12 17:40 UTC, binsee requested changes

2023-10-12 17:40 UTC, binsee commented on README.md
> +|1.3.x|[WeChat-v3.9.2.23](https://github.com/tom-snow/wechat-windows-versions/releases/download/v3.9.2.23/WeChatSetup-3.9.2.23.exe)|
The version should be `1.13.x`

2023-10-18 02:32 UTC, GodMeowIceSun commented on README.md
> +|1.3.x|[WeChat-v3.9.2.23](https://github.com/tom-snow/wechat-windows-versions/releases/download/v3.9.2.23/WeChatSetup-3.9.2.23.exe)|
Also changed now : )

2024-01-19 11:58 UTC, closed without merging